### ISSUE TITLE
Content module is not showing items

### ISSUE THREAD

**Issue by ufoloko** [2sic/2sxc#1568]
[x] bug report => search github for a similar issue before submitting 

[x] admin experience UI

**Current behavior**
I have a site with evoq 9.2, and 2sxc version 9.14 working normally. I upgraded to version 9.30 and everything is working normally.

I have a Content type module in one page, with publish workflow from evoq. I tried to add a new item to content module, and item is saved, but when i publish page, all items are gone. you can see in table mode but in view mode you just can see the initial view, to add items.

This happen just after update 2sxc to 9.30

**Expected behavior**
To be able to add items and publish with evoq content.

**Minimal reproduction of the problem with instructions**
initially I have evoq 9.2 version, with 2sxc version 9.14 and one Content module in one page. I upgraded 2sxc to 9.30 version and tried to add one item to Content, after to publish page, content module is damaged, no one item is showed.

2sxc 9.30
Evoq Content 9.2
Web Browser Chrome 63.0
Language English

**Comment by iJungleboy** [comment]
This is a known bug and should be fixed in 9.31. It's still pre-release because we haven't done our internal pre-release test yet, but it should be ok. Pls test that.

**Comment by ufoloko** [comment]
Hi Jungleboy, i already tested what you suggest, i tried the same with 9.31 version but problem is the same, after publish anything in page, all items for content module dissapear

Regards

**Comment by iJungleboy** [comment]
@ufoloko this sounds bad. could I by any chance see this somewhere? possible with temporary host access? if yes, pls send to info @ or using the contact form on 2sxc.org

**Comment by imhobie** [comment]
Problem still persists with the 2sxc 9.32 LTS release. Evoq 9.0.1/9.2.

pre-exisiting module works fine after 2sxc upgrade, however adding new 2sxc module (app-mode or content-mode) the changes are not published.
