### ISSUE TITLE
One Content Type has "Failed" - How do we recover?

### ISSUE THREAD

**Issue by Accuraty** [2sic/2sxc#1785]
I'm submitting a ...
[x] bug report 

..about
[x] admin experience UI
[x] Content Types or data management
[x] other / unknown

**Current behavior**
We have a custom Content Type we created on a large website. This is an addition and customization in the Content app. After minimal use (it was created the same day and the error occurred within a hour of putting it in to use on a few pages in 2 new Views), it became corrupted or something. Everything else in 2sxc works as expected, but when we click on Destinations to either list/manage the data records or edit the fields, we now get the error you see pictured (Had an error talking to the server (status 500). Message: An error has occurred. If you are an advanced user...) Again, all the other Content Types are fine and we can continue to manage their records and fields. The last action on the Content Type before failing was that we added a new field, a string with a Dropdown. We can also export the full app and when we look at the export of the definition and data for Destinations, it looks okay - or at least we don't see an obvious problem.
 
![image](https://user-images.githubusercontent.com/653301/60270984-204f0f00-98b7-11e9-9bbb-87bb119380e4.png)

We have tried Alt-launching in to the old 9.x Angular 1 UI and that makes no difference. The errors pops up still, almost immediately in either case.
 
Also, the data from Destinations still works and is displaying properly from the Views that access those records.
 
**Expected behavior**
We should be able to at least see a more detailed error somewhere. I have poked around in Insights looking for clues but have not found any.

**Minimal reproduction of the problem with instructions**
I do not know how to help you reproduce this situation. 

**Please tell us about your environment:**
IIS 8+, Windows 2016, everything very up to date.

2sxc version: 10.1 with 2sxcApp_Content_v03.01.01.zip
Browser: all
DNN: 9.3.2

**Comment by iJungleboy** [comment]
This is hard to guess at, as it's not clear what the issue is, and we've never had this before. Note that it could be a simple thing that's already fixed in 10.02 (to be released next week we hope) but otherwise I can't give any guidance without specific info as to what is broken. If you want direct support, please go to https://2sxc.org/en/contact

**Comment by eXistenZe** [comment]
Gonna ask an obvious question, but have you enabled advanced debug and checked dnn events?
Can you export the table/entity?

**Comment by Accuraty** [comment]
> Gonna ask an obvious question, but have you enabled advanced debug and checked dnn events?
> Can you export the table/entity?

There are no obvious questions!! ;)
 
Yes, everything seems to export just fine. The weird thing is that other than that error popping up almost immediately after clicking, I CANNOT find an errors log or reported anywhere.
 
I also did a new thing, I clicked OK on the error (screen shot above). The popup still displays but show no records, but the header does show the add/export/import buttons, so I hit the + button to add a new record, that worked. I saved a test record in to Content Type, then did an export, results here:

``` 
<Entity Type="Destination">
    <Guid>b8954154-22f1-447b-bb87-58e19eebe896</Guid>
    <Language></Language>
    <DestinationName>Test Destination</DestinationName>
    <DestinationPhone>217-555-TEST</DestinationPhone>
    <DestinationLocation>4e620577-9a30-4655-ad0d-a2fe0f6ee5a0</DestinationLocation>
    <DestinationLogo>[""]</DestinationLogo>
    <DestinationFeaturedImage>[""]</DestinationFeaturedImage>
    <DestinationGroup>Other</DestinationGroup>
    <DestinationCoordinator></DestinationCoordinator>
  </Entity>
```
Not sure what else to do.

**Comment by Accuraty** [comment]
Poke around for a while using Insights, couldn't figure much out. Had advanced mode on and finally got a few errors to display in the DevTools Console. As you can see, its the API call to getfields that is failing. But I still don't see any indications as to why.

![image](https://user-images.githubusercontent.com/653301/60404097-04739380-9b6b-11e9-9eff-35fe3ef64367.png)
 
So then I went a step further and tried to open the URL API call in a new tab
 
So this
`/desktopmodules/2sxc/api/eav/contenttype/getfields/?appid=2&staticName=85c4c3ab-4606-4ba5-964c-342bf0ba7b20`

Resulted in this message displaying in the browser: 
`{"Message":"Authorization has been denied for this request."}`

**Comment by iJungleboy** [comment]
@Accuraty you can't call the url directly, because it's missing some security headers (request verification token).

**Comment by iJungleboy** [comment]
What does the insights log show for that API call? and/or the DNN error log? I'm expecting some null-error (something it expects to always be there, but is missing for whatever reason)

**Comment by Accuraty** [comment]
What are the steps to get to that? What Guids would I get/need (in order)?

**Comment by iJungleboy** [comment]
So in case you haven't used insights - check out https://2sxc.org/en/blog/post/using-2sxc-insights 
from there go to logs - and see what the api-call is doing - best post the whole log here.

**Comment by Accuraty** [comment]
For the record: no difference in the 10.02 pre-release. Not that I was expecting any. I realize the problem is some kind of data corruption. I just need to get a handle on how to find it.

**Comment by iJungleboy** [comment]
@Accuraty just fyi: in the 2sxc-insights there are also special pages which show you what's in the cache of an app or what happens when an app loads. This may help you. 

Note that I'll close the issue for now, as it's unclear how to place it, but I'll keep answering questions if you keep posting your findings.

**Comment by Accuraty** [comment]
I have played with Insights and read your article twice, but I seem to be missing some basic info. Where do I start? It seems like I need to know the Entity GUID of the bad Content-Type. I know how to get the Entity Guid of the records in the Content-Type, and I have the Guid of the bad Content-Type. I am sure it is obvious (to you), but I don't understand where to go to find the cache or the logs relating to those. Everything seems to be based on the Guid of the App or AppId? I tried exporting the whole app, but I don't see the AppId there... are there steps or an example walk thru?
