### ISSUE TITLE
Cannot Delete Things

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2205]
I'm submitting a bug report or not sure about the admin experience UI and Content Types or data management.

**Current behavior**
I noticed this earlier today while running 2sxc 11.7.2. Before submitting the issue, I made a backup and upgraded to the newly released 11.7.3, this did not fix it.
 
If you try to delete a field in a Content Type, a permission in a Content Type, or a Content Type, you get an error:
```
Had an error talking to the server (status 405).

if you are an advanced user...
```

Here is a video demoing the problem. Note that this is a clean install of DNN 9.07.02. The Content App is installed, but there were no other apps, 2sxc 11.7.2 was installed and I upgraded it to 11.7.3. I just did Create App and named it "Accu4" then went straight in to create a simple Content Type named TEST4 as you can see here in this zipped video demo.
[2sxc-demo-delete-fails-sNWTyjdbZO.zip](https://github.com/2sic/2sxc/files/5335479/2sxc-demo-delete-fails-sNWTyjdbZO.zip)

**Expected behavior**
I should be able to delete stuff. :)

**Minimal reproduction of the problem with instructions**
Above.

**Please tell us about your environment:**
Self-hosted DNN instance on Windows Server 2016 in SQL 2016.

2sxc version(s): 11.7.2 and 11.7.3 at least
Browser: all
DNN: 9.07.02

**Comment by jeremy-farrance** [comment]
Note that I first discovered this on another project, above was just testing/confirmation, the other proj. was also running DNN 9.07.02 and 2sxc 11.7.2 which I upgraded to 11.7.3. So this is not isolated and the 2 DNN instances were on different servers. Only other module installed (on both) was Evotiva DNN Backup. Other than that, these were clean, minimally used (so far) DNN instances.

**Comment by iJungleboy** [comment]
So the reason you are getting this is most likely because we corrected how things are deleted. Previously the delete used an http `GET` request (which is semantically wrong). It should use an http `DELETE`. 

We changed this recently just to be more aligned to official standards. 

Now AFAIK some old DNNs had the allowed-verbs list wrong in the web.config, which is why we had actually used the GET in the first place. But this (AFAIK) was corrected a long time ago. 
 
I quickly tried to reproduce your issue with a brand new DNN 9.7.2 and the latest 2sxc and everything worked, with `DELETE` verbs. Both cases (delete field and content-type) worked. 

Since our changes are more in-line with the official standards, we would like to keep it this way - unless loads of people are affected. 

Could you check that 

1. this is the problem - and that changing the verbs-list in the web.config to either `*` or adding `DELETE` fixes it
1. is your DNN an upgrade from a long time ago, which would explain the missing verb?

**Comment by jeremy-farrance** [comment]
These are both DNN instances that were deployed this Jul and/or Aug, using DNN 9.6.x or higher. I will check more closely in a few hours and add more soon, thanks!!

**Comment by jeremy-farrance** [comment]
Here (below, bottom) is the handlers section in web.config. I assume you mean the ExtensionlessUrl one, and yes, "DELETE" is in the verbs (on both sites). As an experiment I tried changing the entry to verb="*" and that made no difference, same error.
 
It seems like you are on the right track, in DevTools, the console shows this error: 
```
ERROR n {headers: t, status: 405, statusText: "Method Not Allowed", url: "http://accu4.com/api/2sxc/admin/type/delete?appid=3&staticName=78845c9b-062d-445b-a5f9-e93046e463cc", ok: false, …}
```

I also checked IIS and I see this:
![image](https://user-images.githubusercontent.com/653301/95266208-5be5c200-07f8-11eb-9aea-55b11a0db0aa.png)

I noticed the DNN entry (highlight, Local) is different than the IIS inherited one (green arrow). This is Win Server 2016, so IIS 10. So I tried adding this, but still got the same error. 
```
      <remove name="ExtensionlessUrlHandler-Integrated-4.0" />
      <add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE" type="System.Web.Handlers.TransferRequestHandler" resourceType="Unspecified" requireAccess="Script" preCondition="integratedMode,runtimeVersionv4.0" responseBufferLimit="0" />

```
How do I know that the URL is actually mapping to this handler? Hopefully you can spot a fix? If not, any ideas on what else I can try?
```
    <handlers>
      <remove name="WebServiceHandlerFactory-Integrated" />
      <add name="LogoffHandler*" path="Logoff.aspx" verb="*" type="DotNetNuke.Services.Authentication.LogOffHandler, DotNetNuke" preCondition="integratedMode" />
      <add name="RSSHandler" path="RSS.aspx" verb="*" type="DotNetNuke.Services.Syndication.RssHandler, DotNetNuke" preCondition="integratedMode" />
      <add name="LinkClickHandler" path="LinkClick.aspx" verb="*" type="DotNetNuke.Services.FileSystem.FileServerHandler, DotNetNuke" preCondition="integratedMode" />
      <add name="CaptchaHandler" path="*.captcha.aspx" verb="*" type="DotNetNuke.UI.WebControls.CaptchaHandler, DotNetNuke" preCondition="integratedMode" />
      <add name="UserProfilePageHandler" path="User.aspx" verb="*" type="DotNetNuke.Services.UserProfile.UserProfilePageHandler, DotNetNuke" preCondition="integratedMode" />
      <add name="DnnImageHandler" path="DnnImageHandler.ashx" verb="*" type="DotNetNuke.Services.GeneratedImage.DnnImageHandler, DotNetNuke" preCondition="integratedMode" />
      <remove name="ExtensionlessUrl-Integrated-4.0" />
      <add name="ExtensionlessUrl-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
      <add name="SitemapHandler" path="Sitemap.aspx" verb="*" type="DotNetNuke.Services.Sitemap.SitemapHandler, DotNetNuke" preCondition="integratedMode" />
      <add name="ClientDependencyHandler" verb="*" path="DependencyHandler.axd" type="ClientDependency.Core.CompositeFiles.CompositeDependencyHandler, ClientDependency.Core" preCondition="integratedMode" />
      <add name="SimpleWebFarmSynchronizationHandler" verb="*" path="SimpleWebFarmSync.aspx" type="DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider.SimpleWebFarmSynchronizationHandler, DotNetNuke.Providers.Caching.SimpleWebFarmCachingProvider" preCondition="integratedMode" />
    </handlers>
```

**Comment by iJungleboy** [comment]
Could it be the WebDAV classic? https://stackoverflow.com/questions/26410041/http-error-405-method-not-allowed-error-with-web-api

**Comment by jeremy-farrance** [comment]
Okay, I can confirm this server did have WebDAV installed. I have now removed it. However, it is still happening, I still cannot delete. 
 
I also tried adding:
`<remove name="WebDAV" />`
To the handlers in web.config, that didn't make a difference either.

Is it possible there is a different web.config in play here? Given the URL-path to the /delete command?
`/api/2sxc/admin/type/delete?appid=5&staticName=7893a081-2231-49f8-a7d5-160e863834a4`
 
Do you have any suggestions or further debugging ideas? 

Is there some way to debug/see exactly WHICH handler (or handlers) is catching and processing the /delete in this case?

**Comment by iJungleboy** [comment]
I'm not too versed with this, but AFAIK if you google webdav/iis/delete you'll find some more instructions - I believe there are 2 places than need disabling or something.

**Comment by jeremy-farrance** [comment]
Okay, it was definitely WebDAV. Removing it via Server Roles didn't work. Removing it in web.config didn't work. 

**Important: if someone else reads and needs to try this, a) backup your server and b) make a backup of applicationHost.config before you make changes. And if you do not know where this file is or how to get your edits to save, re-read a and b again.**
 
What did finally work was manually editing IIS' applicationHost.config file and adding 'remove' in both <modules> and <handlers>.

```
...
      <remove name="WebDAVModule" />
    </modules>

...
      <remove name="WebDAV" />
    </handlers>
```

**Comment by jeremy-farrance** [comment]
So that leaves me with the unanswered question - how/why does WebDAV get to handle that URL before (or instead of) "ExtensionlessUrl-Integrated-4.0"?

**Comment by iJungleboy** [comment]
Glad you could solve it - and I don't know exactly how the pipeline works, but obviously WebDAV got there first...

**Comment by jeremy-farrance** [comment]
In case someone else finds this problem and does NOT have access to the server-wide IIS/dotnet config, you can also do it per site in Dnn's web.config:
![image](https://user-images.githubusercontent.com/653301/102403635-30c3df80-3fac-11eb-9643-4c50ae0872d0.png)

See [Issue 2303](https://github.com/2sic/2sxc/issues/2303)

**Comment by david-poindexter** [comment]
For others running into this and looking for a UI-based way to handle this, you can simply turn off (remove) the "WebDAV Publishing" feature in IIS.

You can access via:
Server Manager > IIS > Roles and Features
* Find "WebDAV Publishing" in the list and right-click "Remove Role or Feature".
* Then traverse the tree `Internet Information Services > World Wide Web Services > Common HTTP Features > WebDAV Publishing` and uncheck it.
* Continue through wizard and remove the feature.

**Comment by skarpik** [comment]
With DNN v9.13.00 website and 2sxc v16.7.0, this problem no longer exists. So no longer a need for a workaround.

**Comment by iJungleboy** [comment]
@skarpik I believe a long time ago we changed the HTTP-Verb to be "post" even for the delete. So it's technically not 100% the recommended way, but it doesn't cause the problems mentioned above ;)

**Comment by D0rk80** [comment]
thanks running dnn10 had this issue was driving me crazy
the below worked!!
[david-poindexter](https://github.com/david-poindexter)
You can access via:
Server Manager > IIS > Roles and Features

Find WebDAV Publishing in the list.
Right-click and select Remove Role or Feature

**Comment by jeremy-farrance** [comment]
WebDAV is not a DNN thing in any way. It only gets introduced by the host server. If the Windows Server (think add Features/Roles) has WebDAV added (its available under the IIS stuff), then it interferes with DNN or ASP.NET's extensionless URLs as detailed above.

**Comment by tvatavuk** [comment]
Thanks for the heads-up. I’ve double-checked, but so far I haven’t found any significant differences in how DNN 10 handles DELETE requests compared to DNN 9 (commonly blocked by installed WebDAV IIS component).

![Image](https://github.com/user-attachments/assets/fd151464-1463-4acc-a0c6-b34e41f34a23)

In our tests, DELETE requests in 2sxc are working as expected in DNN 10 as well. However, it's still essential to disable WebDAV (as previously documented), since its presence can block or override DELETE operations — not just for 2sxc, but for any DNN module relying on those HTTP verbs.

If anyone's seeing inconsistent behavior, I’d also suggest confirming that WebDAV is fully removed from the web.config and/or IIS handler mappings (thx @jeremy-farrance 👍).
