### ISSUE TITLE
No bleu edit buttons for non site administrator

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#502]
Only the site administrator get the bleu edit buttons for edeting content. The buttons are not visible for a user with edit rights. There are also not vsible when the user has the "2sxc designers" role. The buttons are still gone in edit mode

![schermafbeelding 2015-12-02 om 17 18 20](https://cloud.githubusercontent.com/assets/13934402/11536485/f3cf6e94-9918-11e5-89fe-39b7fe83440a.png)

should be

![schermafbeelding 2015-12-02 om 17 21 50](https://cloud.githubusercontent.com/assets/13934402/11536561/3b3e31b6-9919-11e5-94d5-808541e9d3bb.png)

**Comment by iJungleboy** [comment]
Could you help debug a bit more? 

1. Are the helper scripts missing (like the inpage...js)
2. are the menus missing in the page (the <ul ...> lists with the buttons
3. are the JSON tags missing on the module wrapper?

thx!

**Comment by Frankwalraven** [comment]
as a administrator 
j2sxc.api.min.js
and
2sxc4ng.min.js
are loaded
![schermafbeelding 2015-12-02 om 18 01 41](https://cloud.githubusercontent.com/assets/13934402/11537747/c95263fa-991e-11e5-9488-71951deb8248.png)

As a normal user not
![schermafbeelding 2015-12-02 om 18 02 29](https://cloud.githubusercontent.com/assets/13934402/11537764/e828a3ca-991e-11e5-9bd2-2f7336187d66.png)

**Comment by Frankwalraven** [comment]
the menu appears
<img width="247" alt="schermafbeelding 2015-12-02 om 18 41 38" src="https://cloud.githubusercontent.com/assets/13934402/11538928/94f4b94a-9924-11e5-9198-d846a669e70e.png">

but only the the button edit template works. The other buttons don't react.

**Comment by iJungleboy** [comment]
That's strange. The inclusion of these is based on

'DotNetNuke.Security.Permissions.ModulePermissionController.CanEditModuleContent(ModuleContext.Configuration)'

which sounds correct. Could you do some research and find out if there is something wrong? You could create some razor-scripts which do some tests based on this, just for a test-run.

**Comment by iJungleboy** [comment]
Note that the other buttons try to access the libraries - which are missing.

**Comment by KosVos37** [comment]
Hi Jungleboy,
I take over this call from Frank. I want to do some more research and create razor scripts but can you tell me more explicitly what you want to test? Just run a test with that line. It is not clear to me

**Comment by iJungleboy** [comment]
@KosVos37 thanks for your help. Please find out if the command we're using is delivering the wrong result, or if we should use a different command. So the question is, does 
`'DotNetNuke.Security.Permissions.ModulePermissionController.CanEditModuleContent(...)`
behave as expected (and return true when a non-admin user has edit rights on the module) or not, and if not, what command we should use to discover this.

**Comment by iJungleboy** [comment]
@KosVos37 You had a question regarding your code - please do that in this issue tracker. Your code was somethnig like

@using DotNetNuke.Services.ClientCapability
@using System.Text
@using System.Text.RegularExpressions
@using DotNetNuke.Security.Permissions
@{
var controller = new DotNetNuke.Security.Permissions.ModulePermissionController();
var module = controller.Instance.GetModule(591, Null.NullInteger, true);
result = module != null && ModulePermissionController.CanEditModuleContent(module);


My guess is that a) you should have used var module = Dnn.Module; or similar, and that the CanEditModule probably doesn't want the module but the module.Configuration - but i'm not sure.

**Comment by Frankwalraven** [comment]
I found something.
It looks like 2sxc looks only to the user rights of a module. When I give a user the rights to edit a module everything works for the specific module. The buttons are displayed etc.  When the user rights are set to a page and for the module is set that the user rights are inherit from the page rights, the edit functions from 2sxc are not displayed. 

Not 2sxc functions/modules in edit mode work normal  when only page rights are set

**Comment by iJungleboy** [comment]
That's great to know, and sounds bad. It seems that DNN doesn't know a user can edit the module if he can "only" edit the page :(. Please delve deeper, maybe we can just add some more lines of code - would love it if you figured it out :)

**Comment by Frankwalraven** [comment]
For other modules - non 2sxc - everything works correct. When I set edit rights on page level, I can edit a HTML module and all other non 2sxc modules

**Comment by iJungleboy** [comment]
@Frankwalraven that sounds great. I would appreciate it if you would check the source code on one of these to get me the code they use for security check. Probably just a line or two more, but it would help us if you could find it :).

**Comment by KosVos37** [comment]
This is how the rights are checked in the ModerationServiceController controller:
        [HttpPost]
        [ValidateAntiForgeryToken]
        [DnnModuleAuthorize(AccessLevel = SecurityAccessLevel.View)]
        [SupportedModules("Social Groups")]
        public HttpResponseMessage LeaveGroup(RoleDTO postData)
        {
            var success = false;
            try  {
                if (UserInfo.UserID >= 0 && postData.RoleId > 0) {
                    _roleInfo = RoleController.Instance.GetRoleById(PortalSettings.PortalId, postData.RoleId);
                    if (_roleInfo != null) {
                        if (UserInfo.IsInRole(_roleInfo.RoleName)) {  <<<< Test on the Edit content role
                            RoleController.DeleteUserRole(UserInfo, _roleInfo, PortalSettings, false); }
                        success = true;
             }}}
            catch (Exception exc) {
                Logger.Error(exc); return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, exc);
            }
            if(success) {
                return Request.CreateResponse(HttpStatusCode.OK, new {Result = "success"}); }
            
            return Request.CreateErrorResponse(HttpStatusCode.InternalServerError, "Unknown Error");}

We are just starting with DNN and for the authorization we use the UI possibilities. I hope you this answer will help you a bit.

**Comment by iJungleboy** [comment]
This doesn't help much, as it's not code in a page but in a web service.

**Comment by KosVos37** [comment]
Sorry for that, but we found an article that might be useful. As I said we are at the moment not too familiar with the Dnn core.
The article : "http://www.dnnsoftware.com/community-blog/cid/134683/authorization-in-the-new-dnn-services-framework"

**Comment by iJungleboy** [comment]
nope, sorry, doesn't help.

**Comment by iJungleboy** [comment]
I think I fixed it - please try the beta 08.00.10 (won't be official release, but please test/feedback)

**Comment by KosVos37** [comment]
Hello iJungleboy, I understand that you fixed the problem with blue buttons and saw it marked in git  "2sic_2SexyContent.dnn -> version Increased version number to 08.00.10" but until now there is no download. Where can I find this download. Lastest Version is the .09 version. Or must I build it myself from the repository?

**Comment by iJungleboy** [comment]
will release in 1-2 hours

**Comment by Frankwalraven** [comment]
Hi IJunglebuy,
I test the the 8.00.10 version. It works still not for 100% correct. When a user has now edit rights on page level and for one module on the page we don't inherit the rights from the page and set no edit rights for that module for the user, this user can still edit the module.

**Comment by iJungleboy** [comment]
that sucks - though it is a fairly special setup. I would love to fix it some more, but I believe it's actually a DNN bug. Since asking the API "does the user have edit permissions on this module" seems to tell me "no" when the module doesn't have the permissions assigned directly. 

For now I'll have to focus on other topics. If you can find out the better (more reliable) way of asking DNN the "could he edit" question I'll look into it again, but I'll need the exact lines of code. If I have to research it myself or read articles about it or try with code which might do the job, 
 I won't spend the time on it for now. If you can get me the exact code I'll be happy to merge it into the code base.
